var c = [{"uname_in_bbs":"szmsm"            },  
{"uname_in_bbs":"目光呆滞的润土"          },  
{"uname_in_bbs":"原始资料"             },  
{"uname_in_bbs":"perry点点头"         },  
{"uname_in_bbs":"kunbrother"       },  
{"uname_in_bbs":"Softwiki"         },  
{"uname_in_bbs":"稀饭配咸菜"            },  
{"uname_in_bbs":"myqzero"          },  
{"uname_in_bbs":"jhi2"             },  
{"uname_in_bbs":"xuzhuoyeah"       },  
{"uname_in_bbs":"miaoze"           },  
{"uname_in_bbs":"dokmyong"         },  
{"uname_in_bbs":"simch"            },  
{"uname_in_bbs":"Rockefeller1983"},
{"uname_in_bbs":"kunbrother"       },  
{"uname_in_bbs":"dokmyong"         },  
{"uname_in_bbs":"短命的乌龟"            },  
{"uname_in_bbs":"tinners"          },  
{"uname_in_bbs":"20301314"         },  
{"uname_in_bbs":"Rockefeller1983"},
{"uname_in_bbs":"Rockefeller1983"},
{"uname_in_bbs":"抱元守一之深圳狼"         },  
{"uname_in_bbs":"一切皆可能"            },  
{"uname_in_bbs":"tutinga"          },  
{"uname_in_bbs":"学着"               },  
{"uname_in_bbs":"chenglong1121975"
},{"uname_in_bbs":"yhxe"             },  
{"uname_in_bbs":"曾经的小E"            },  
{"uname_in_bbs":"要胖点"              },  
{"uname_in_bbs":"要胖点"              },  
{"uname_in_bbs":"灵啃"               },  
{"uname_in_bbs":"那年我十六"            },  
{"uname_in_bbs":"kunbrother"       },  
{"uname_in_bbs":"汉江水头"             },  
{"uname_in_bbs":"汉江水头"             },  
{"uname_in_bbs":"忧郁的冬天"            },  
{"uname_in_bbs":"yhxe"             },  
{"uname_in_bbs":"目光呆滞的润土"          },  
{"uname_in_bbs":"dokmyong"         },  
{"uname_in_bbs":"冰雪化骨"             },  
{"uname_in_bbs":"yhxe"             },  
{"uname_in_bbs":"sunfupai"         },  
{"uname_in_bbs":"kunbrother"       },  
{"uname_in_bbs":"kunbrother"       },  
{"uname_in_bbs":"目光呆滞的润土"          },  
{"uname_in_bbs":"灵啃"               },  
{"uname_in_bbs":"灵啃"               },  
{"uname_in_bbs":"softwiki"         },  
{"uname_in_bbs":"dokmyong"         },  
{"uname_in_bbs":"tinners"          },  
{"uname_in_bbs":"目光呆滞的润土"          },  
{"uname_in_bbs":"catofqueen"       },  
{"uname_in_bbs":"II横绝四海II"         },  
{"uname_in_bbs":"lixianyaan"       },  
{"uname_in_bbs":"xuzhuoyeah"       },  
{"uname_in_bbs":"原始资料"             },  
{"uname_in_bbs":"hbzlg2001"        },  
{"uname_in_bbs":"鲁迅故乡"             },  
{"uname_in_bbs":"love紫藤"           },  
{"uname_in_bbs":"chenglong1121975"},
{"uname_in_bbs":"忧郁的冬天"            },  
{"uname_in_bbs":"chenglong1121975"},
{"uname_in_bbs":"冰糖葫"              },  
{"uname_in_bbs":"一身羽毛"             },  
{"uname_in_bbs":"五湖一帆"             },  
{"uname_in_bbs":"乌夜啼"              },  
{"uname_in_bbs":"乌夜啼"              },  
{"uname_in_bbs":"目光呆滞的润土"          },  
{"uname_in_bbs":"catofqueen"       },  
{"uname_in_bbs":"ngo"              },  
{"uname_in_bbs":"maomaoa"          },  
{"uname_in_bbs":"skybabe"          },  
{"uname_in_bbs":"冰雪化骨"             },  
{"uname_in_bbs":"chenglong1121975"},
{"uname_in_bbs":"明天要许愿"            },  
{"uname_in_bbs":"风筝飞呀飞呀"           },  
{"uname_in_bbs":"大默荒烟"             },  
{"uname_in_bbs":"bl790618"         },  
{"uname_in_bbs":"jinfat"           },  
{"uname_in_bbs":"岩商"               },  
{"uname_in_bbs":"softwiki"         },  
{"uname_in_bbs":"abala店主"          },  
{"uname_in_bbs":"sollion"          },  
{"uname_in_bbs":"金牌海角"             },  
{"uname_in_bbs":"liming198"        },  
{"uname_in_bbs":"8凤凰台上忆吹萧8"        },  
{"uname_in_bbs":"zdfjx"            },  
{"uname_in_bbs":"陪你游天下"            },  
{"uname_in_bbs":"飘隐君"              },  
{"uname_in_bbs":"飘隐君"              },  
{"uname_in_bbs":"潜龙勿用有悔"           },  
{"uname_in_bbs":"潜龙勿用有悔"           },  
{"uname_in_bbs":"kunbrother"       },  
{"uname_in_bbs":"打工开店人"            },  
{"uname_in_bbs":"原始资料"             },  
{"uname_in_bbs":"bl790618"         },  
{"uname_in_bbs":"wxyty"            },  
{"uname_in_bbs":"bl790618"         },  
{"uname_in_bbs":"bl790618"         },  
{"uname_in_bbs":"杭州浪子"             },  
{"uname_in_bbs":"目光呆滞的小军"          },  
{"uname_in_bbs":"kae家"             },  
{"uname_in_bbs":"bl790618"         },  
{"uname_in_bbs":"kunbrother"       },  
{"uname_in_bbs":"学着"               },  
{"uname_in_bbs":"稀饭配咸菜"            },  
{"uname_in_bbs":"haisns"           },  
{"uname_in_bbs":"陪你游天下"            },  
{"uname_in_bbs":"岩商"               },  
{"uname_in_bbs":"新手邓文"             },  
{"uname_in_bbs":"江东_周郎"            },  
{"uname_in_bbs":"目光呆滞的小军"          },  
{"uname_in_bbs":"bl790618"         },  
{"uname_in_bbs":"hqshlhs"          },  
{"uname_in_bbs":"niehua30"         },  
{"uname_in_bbs":"高原总部"             },  
{"uname_in_bbs":"东湖觉皇"             },  
{"uname_in_bbs":"Softwiki"         },  
{"uname_in_bbs":"chenglong1121975"},
{"uname_in_bbs":"难道结束吗"            },  
{"uname_in_bbs":"草原狼老斌"            },  
{"uname_in_bbs":"jinfat"           },  
{"uname_in_bbs":"岩商"               },  
{"uname_in_bbs":"catofqueen"       },  
{"uname_in_bbs":"maomaoa"          },  
{"uname_in_bbs":"longericher"      },  
{"uname_in_bbs":"杨铭7"              },  
{"uname_in_bbs":"冰雪化骨"             },  
{"uname_in_bbs":"冰雪化骨"             },  
{"uname_in_bbs":"目光呆滞的小军"          },  
{"uname_in_bbs":"杨铭7"              },  
{"uname_in_bbs":"目光呆滞的小军"          },  
{"uname_in_bbs":"目光呆滞的小军"          },  
{"uname_in_bbs":"个性手表"             },  
{"uname_in_bbs":"kunbrother"       },  
{"uname_in_bbs":"草原狼老斌"            },  
{"uname_in_bbs":"德庆的森林"            },  
{"uname_in_bbs":"maomaoa"          },  
{"uname_in_bbs":"浪天下"              },  
{"uname_in_bbs":"13007398419"      },  
{"uname_in_bbs":"惑8618"            },  
{"uname_in_bbs":"原始资料"             },  
{"uname_in_bbs":"rlf1"             },  
{"uname_in_bbs":"稀饭配咸菜"            },  
{"uname_in_bbs":"happywhr"         },  
{"uname_in_bbs":"岩商"               },  
{"uname_in_bbs":"jfwyyt"           },  
{"uname_in_bbs":"卡卡松"              },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"岩商"               },  
{"uname_in_bbs":"kunbrother"       },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"kunbrother"       },  
{"uname_in_bbs":"稀饭配咸菜"            },  
{"uname_in_bbs":"目光呆滞的润土"          },  
{"uname_in_bbs":"kunbrother"       },  
{"uname_in_bbs":"kae家"             },  
{"uname_in_bbs":"kae家"             },  
{"uname_in_bbs":"iEgO"             },  
{"uname_in_bbs":"jfwyyt"           },  
{"uname_in_bbs":"浪天下"              },  
{"uname_in_bbs":"lzllzlmm"         },  
{"uname_in_bbs":"sumichael"        },  
{"uname_in_bbs":"云中盟"              },  
{"uname_in_bbs":"wikeywin"         },  
{"uname_in_bbs":"hentiansi"        },  
{"uname_in_bbs":"yehaizi304"       },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"lijie0163"        },  
{"uname_in_bbs":"原始资料"             },  
{"uname_in_bbs":"wxyty"            },  
{"uname_in_bbs":"catofqueen"       },  
{"uname_in_bbs":"yingshuai"        },  
{"uname_in_bbs":"投机之王"             },  
{"uname_in_bbs":"岩商"               },  
{"uname_in_bbs":"hentiansi"        },  
{"uname_in_bbs":"目光呆滞的小军"          },  
{"uname_in_bbs":"hentiansi"        },  
{"uname_in_bbs":"寻找小菊灯"            },  
{"uname_in_bbs":"目光呆滞的小军"          },  
{"uname_in_bbs":"Adam521"          },  
{"uname_in_bbs":"目光呆滞的润土"          },  
{"uname_in_bbs":"怀念昨日的我"           },  
{"uname_in_bbs":"对比"               },  
{"uname_in_bbs":"亦方亦圆"             },  
{"uname_in_bbs":"怀念昨日的我"           },  
{"uname_in_bbs":"寻找小菊灯"            },  
{"uname_in_bbs":"怀念昨日的我"           },  
{"uname_in_bbs":"xuzhuoyeah"       },  
{"uname_in_bbs":"左岸香烟"             },  
{"uname_in_bbs":"目光呆滞的润土"          },  
{"uname_in_bbs":"亦方亦圆"             },  
{"uname_in_bbs":"风云三十而立"           },  
{"uname_in_bbs":"风云三十而立"           },  
{"uname_in_bbs":"hqshlhs"          },  
{"uname_in_bbs":"寻找小菊灯"            },  
{"uname_in_bbs":"kunbrother"       },  
{"uname_in_bbs":"草原狼老斌"            },  
{"uname_in_bbs":"风云三十而立"           },  
{"uname_in_bbs":"tinners"          }] ;


//var c = require('./page12_guhun.json');
//console.log(c.length);

c.forEach(function(c1) {
	var i = c.indexOf(c1);
	//console.log(i);
	
	//print(c1['uname_in_bbs']);
  var userid =  0;
  var uname = c1['uname_in_bbs'];
	var user = db.users.find({"uname_in_bbs":uname});
	while(user.hasNext()){
		var temp = user.next();
		//printjson(user.next());
		var userid = temp['uid_in_bbs'];
		//db.pages.update({"page_index":12,"page_id":{"$gte":12002,"$lte":12211},"user_id":null},{$set:{"user_id":userid}},{multi:true});
		db.pages.update({"page_index":12,"page_id":{"$gte":12002,"$lte":12211},"user_id":null,"user_name":uname},{$set:{"user_id":userid}},{multi:true});
		//db.pages.find({"page_index":12,"page_id":{"$gte":12002,"$lte":12211},"user_id":null});
		//if (userid == null) {
	      //printjson({"uname":uname,"uid":userid});
		//}
		
	}

	//print user = null

  

	
});

